ebay_watches:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: lmu_local
      port: 5432
      dbname: dbt
      schema: main
      threads: 1
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
